/**
 ******************************************************************************
 * @file    isp_param_conf_template.h
 * @author  AIS Application Team
 * @brief   Header file for IQT parameters of the ISP middleware - template
 * This file must be copied into the application folder.
 * This file can be:
 * - either generated by the IQTT_generate_h.py script
 * - either manually updated by setting the IQ parameter values
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/* Define to prevent recursive inclusion -------------------------------------*/
#ifndef __ISP_PARAM_CONF__H
#define __ISP_PARAM_CONF__H

/* Minimal configuration (demosaicing + decimation = 1) of DUMMY sensor */
static const ISP_IQParamTypeDef ISP_IQParamCacheInit_DUMMY = {
    .sensorGainStatic = {
        .gain = 0,
    },
    .sensorExposureStatic = {
        .exposure = 0,
    },
    .AECAlgo = {
        .enable = 0,
        .exposureCompensation = EXPOSURE_TARGET_0_0_EV,
    },
    .statRemoval = {
        .enable = 0,
        .nbHeadLines = 0,
        .nbValidLines = 0,
    },
    .badPixelStatic = {
        .enable = 0,
        .strength = 0,
    },
    .badPixelAlgo = {
        .enable = 0,
        .threshold = 0,
    },
    .blackLevelStatic = {
        .enable = 0,
        .BLCR = 0,
        .BLCG = 0,
        .BLCB = 0,
    },
    .demosaicing = {
        .enable = 1,
        .type = ISP_DEMOS_TYPE_RGGB,
        .peak = 0,
        .lineV = 0,
        .lineH = 0,
        .edge = 0,
    },
    .ispGainStatic = {
        .enable = 0,
        .ispGainR = 0,
        .ispGainG = 0,
        .ispGainB = 0,
    },
    .colorConvStatic = {
        .enable = 0,
        .coeff = { { 0, 0, 0, }, { 0, 0, 0, }, { 0, 0, 0, }, }
    },
    .AWBAlgo = {
        .enable = 0,
        .id = { "", "", "", "", "", },
        .referenceColorTemp = { 0, 0, 0, 0, 0, },
        .ispGainR = { 0, 0, 0, 0, 0, },
        .ispGainG = { 0, 0, 0, 0, 0, },
        .ispGainB = { 0, 0, 0, 0, 0, },
        .coeff = {
            { { 0, 0, 0, }, { 0, 0, 0, }, { 0, 0, 0, }, },
            { { 0, 0, 0, }, { 0, 0, 0, }, { 0, 0, 0, }, },
            { { 0, 0, 0, }, { 0, 0, 0, }, { 0, 0, 0, }, },
            { { 0, 0, 0, }, { 0, 0, 0, }, { 0, 0, 0, }, },
            { { 0, 0, 0, }, { 0, 0, 0, }, { 0, 0, 0, }, },
        },
    },
    .contrast = {
        .enable = 0,
        .coeff.LUM_0 = 0,
        .coeff.LUM_32 = 0,
        .coeff.LUM_64 = 0,
        .coeff.LUM_96 = 0,
        .coeff.LUM_128 = 0,
        .coeff.LUM_160 = 0,
        .coeff.LUM_192 = 0,
        .coeff.LUM_224 = 0,
        .coeff.LUM_256 = 0,
    },
    .statAreaStatic = {
        .X0 = 0,
        .Y0 = 0,
        .XSize = 0,
        .YSize = 0,
    },
    .gamma = {
        .enablePipe1 = 0,
        .enablePipe2 = 0,
    },
};

static const ISP_IQParamTypeDef* ISP_IQParamCacheInit[] = {
    &ISP_IQParamCacheInit_DUMMY
};

#endif /* __ISP_PARAM_CONF__H */
